[package]
name = "websocket-rust-swift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wsrustswift"
crate-type = [ "staticlib" ]

[dependencies]
websocket = "0.26.4"
